### ISSUE TITLE
No Code in Repo

### ISSUE THREAD

**Issue by syamsathyan** [danships/genie-point#1]

**Comment by danships** [comment]
You are correct. I am still working on this project, first https://github.com/matueranet/genie-ai needs to be working correctly before I can continue on this repo.

**Comment by syamsathyan** [comment]
Thanks, I would like to contribute on certain areas like iot protocols, profanity etcOn Mar 3, 2017 4:50 AM, matueranet <notifications@github.com> wrote:You are correct. I am still working on this project, first https://github.com/matueranet/genie-ai needs to be working correctly before I can continue on this repo.

**Comment by danships** [comment]
@syamsathyan Ok, sounds great! I was focusing on https://github.com/matueranet/genie-router but am moving back to genie-ai, so after that I am going back to genie-point, which is basically a CLI wrapper around genie-ai. Maybe some of the items you want to contribute with also have place in genie-router.

**Comment by syamsathyan** [comment]
Sounds good ..On Mar 3, 2017 5:14 AM, matueranet <notifications@github.com> wrote:@syamsathyan Ok, sounds great! I was focusing on https://github.com/matueranet/genie-router but am moving back to genie-ai, so after that I am going back to genie-point, which is basically a CLI wrapper around genie-ai. Maybe some of the items you want to contribute with also have place in genie-router.
